# syntax=docker/dockerfile:1

FROM dhi.io/node:25-dev AS node

FROM dhi.io/golang:1.25-dev AS build

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/bin/npm /usr/local/bin/npm
COPY --from=node /usr/local/bin/npx /usr/local/bin/npx
COPY --from=node /usr/local/bin/corepack /usr/local/bin/corepack
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /usr/local/include/node /usr/local/include/node

ENV GOPATH=/go
ENV PATH=/usr/local/go/bin:$PATH

WORKDIR /workspace

LABEL org.opencontainers.image.title="Arcane Build"
LABEL org.opencontainers.image.description="Arcane build image with dhi node-dev and go-dev toolchains"
LABEL org.opencontainers.image.source="https://github.com/getarcaneapp/arcane"
